# https://github.com/haritos90/shadowrocket-config-files

[General]

ipv6 = false
prefer-ipv6 = false
private-ip-answer = true
dns-direct-system = true
dns-direct-fallback-proxy = true
dns-server = system
fallback-dns-server = system
hijack-dns = :53
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32

#tun-included-routes =

#always-real-ip = *

icmp-auto-reply = false
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT

# ---URL for Config file updates---
update-url = https://raw.githubusercontent.com/haritos90/shadowrocket-config-files/master/h90_direct.conf

[Rule]

FINAL,DIRECT
